# This file requires the VSCode REST Client extension to be installed.
# dotenv variables require the .env file to be in the same directory as this file.
# For debugging, rest-client.previewOption should be set to exchange to see request/response headers.

# Variables
@baseUrl = {{$dotenv BASE_URL}}
@apiKey = {{$dotenv API_KEY}}

# POST CC with x-api-key header
POST {{baseUrl}}/api/transactions/creditcard
content-type: application/json
x-api-key: {{apiKey}}

    {
        "phoneNo": "4805551212",
        "accountNo": "6112fd5867302f001e204701",
        "leadID": "12345",
        "creditCardNo": "4532015112830366",
        "creditCardExp": "0625",
        "creditCardSec": "1111"
    }

###

# POST CC with x-api-key querystring
POST {{baseUrl}}/api/transactions/creditcard?x-api-key={{apiKey}}
content-type: application/json

    {
        "phoneNo": "4805551212",
        "accountNo": "6112fd5867302f001e204701",
        "leadID": "12345",
        "creditCardNo": "4532015112830366",
        "creditCardExp": "0625",
        "creditCardSec": "1111"
    }

###

# POST ACH with x-api-key header
POST {{baseUrl}}/api/transactions/ach
content-type: application/json
x-api-key: {{apiKey}}

    {
        "phoneNo": "4805551212",
        "accountNo": "6112fd5867302f001e204701",
        "leadID": "12345",
        "achRoutingNo": "122100024",
        "achAccountNo": "918709270"
    }

###

# POST ACH with x-api-key querystring
POST {{baseUrl}}/api/transactions/ach?x-api-key={{apiKey}}
content-type: application/json

    {
        "phoneNo": "4805551212",
        "accountNo": "6112fd5867302f001e204701",
        "leadID": "12345",
        "achRoutingNo": "122100024",
        "achAccountNo": "918709270"
    }

###

# GET ACH with x-api-key querystring and data as querystring
GET {{baseUrl}}/api/transactions/ach
    ?x-api-key={{apiKey}}
    &phoneNo=4805551212
    &accountNo=6112fd5867302f001e204701
    &leadID=12345
    &achRoutingNo=122100024
    &achAccountNo=918709270

###

# GET CreditCard with x-api-key querystring and data as querystring
GET {{baseUrl}}/api/transactions/creditcard
    ?x-api-key={{apiKey}}
    &phoneNo=4805551212
    &accountNo=6112fd5867302f001e204701
    &leadID=12345
    &creditCardNo=4532015112830366
    &creditCardExp=0625
    &creditCardSec=1111

###

# GET CreditCard with x-api-key header and data as querystring
GET {{baseUrl}}/api/transactions/creditcard
    ?creditCardSec=1111
    &creditCardNo=4532015112830366
    &accountNo=6112fd5867302f001e204701
    &creditCardExp=0625
    &phoneNo=4805551212
    &leadID=256106
x-api-key: {{apiKey}}

###